name: trabalholp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-210.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.7+1
  url_launcher: ^6.0.12
  flutter_form_builder: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
